version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12.9

    steps:
      - checkout
      # - restore_cache:
      #     key: aemworkflow
      # - run:
      #     name: Build and run test environment
      #     command: |
      #       chmod +x tests/_run-tests.sh
      #       bash tests/_run-tests.sh
            
      # - save_cache: 
      #     key: aemworkflow
      #     paths:
      #       - $HOME
