version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.9

    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: Build and run test environment
          command: |
            source ./ci_gdal_install.sh
            pip install -r requirements-dev.txt
            pytest tests/

      - run:
          name: Upload test results to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) \
              -t $CODECOV_TOKEN \
              -f test-results/results.xml \
              -F unittests \
              -B main
