name: aemworkflow

on: [pull_request]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: python3-pip gdal-bin libgdal-dev openmpi-bin libopenmpi-dev libblas-dev liblapack-dev libatlas-base-dev gfortran libproj-dev
        version: 1.0
    - name: Set up Python 3.12.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.9
        cache: pip
    - name: Install dependencies
      run: |
        pip install GDAL==$(gdal-config --version)
        pip install pytest codecov coverage pytest-cov
        pip install -r requirements.txt
    - name: Run tests with coverage
      run: |
        pytest --cov --cov-report xml:results.xml --cov-report json --disable-warnings
    - name: Get Cover
      uses: orgoro/coverage@v3.2
      with:
          coverageFile: results.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: .8
