name: aemworkflow

on: [pull_request]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: openmpi-bin libopenmpi-dev libblas-dev liblapack-dev libatlas-base-dev gfortran libproj-dev
        version: 1.0
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@main
      with:
        path: |
          /home/runner/miniconda/envs/aemworkflow-scripts
        key: anaconda
    - name: Build and run test environment
      run: |
        source tests/_run-tests.sh
    - name: Get Cover 
      uses: orgoro/coverage@v3.2
      with:
          coverageFile: test-results/results.xml
          token: ${{ secrets.GITHUB_TOKEN }}
