# This workflow is setup by Fei Zhang to use Github Actions 2020-09-14
# Updated by Melyn Roberts 2025 June to run tests using Anaconda3-2021.11 and Python and package versions designated in linux startup script

name: aemworkflow

on: [push]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: openmpi-bin libopenmpi-dev libblas-dev liblapack-dev libatlas-base-dev gfortran libproj-dev
        version: 1.0
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@main
      with:
        path: |
          /home/runner/work/aemworkflow-scripts
          /usr/share/miniconda/envs/aemworkflow-scripts
        key: anaconda
    - name: Build and run test environment
      run: |
        source tests/_run-tests.sh
    - name: Get Cover 
      uses: orgoro/coverage@v3.2
      with:
          coverageFile: path/to/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
