name: aemworkflow

on: [pull_request]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: openmpi-bin libopenmpi-dev libblas-dev liblapack-dev libatlas-base-dev gfortran libproj-dev
        version: 1.0
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@main
      with:
        path: |
          /home/runner/miniconda/envs/aemworkflow-scripts
        key: anaconda
    - name: Build test environment
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        source tests/_run-tests.sh
    - name: Run tests with coverage
      run: |
        eval "$(conda shell.bash hook)"
        conda init bash
        source ~/.bashrc
        conda activate /home/runner/miniconda/envs/aemworkflow-scripts
        pip install -r requirements-dev.txt
        pytest tests --cov-report xml:tests/results.xml
        ls -al tests
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: results.xml
